### ISSUE TITLE
Error with log output

### ISSUE THREAD

**Issue by bossanova808** [caronc/nzb-subliminal#45]
I think this is possibly a bug in log output - here's a log of it looking for subs for a TV series, Cardinal, as called by a manual call:

`C:\Utilities\SAB Post Processing Scripts>python Subliminal.py -f "I:\TV Library 04\Cardinal"`

....this issue is that is seems to be looking for `TV Library` as the series name, rather than the series `Cardinal` - or so the log seems to imply.  But I've checked the subs downloaded, and they are indeed for Cardinal.  So think it's more of a log output issue than a real issue maybe...

Also - no idea what the the invalid file messages is about, there is no invalid file in there (and certainly not with such a funky name!)

Also - super super OCD level minor, but there's a type on the word service - `Addic7ed using authentication serice.`

```
2018-01-22 12:17:22,542 - 16872 - INFO - Found 9 matched file(s).
2018-01-22 12:17:22,542 - 16872 - INFO - Using advanced search mode
2018-01-22 12:17:22,796 - 16872 - WARNING - Skipping - Invalid file: 㩉呜⁖楌牢牡⁹㐰䍜牡楤慮屬敓獡湯〠就慃摲湩污ⴠ匠㄰ぅ‱‭慃摲湩污圠䉅䱄ㄭ㠰瀰洮癫
2018-01-22 12:17:22,855 - 16872 - INFO - Scanning video 'Cardinal - S01E03 - Edie and Eric WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-22 12:17:22,905 - 16872 - INFO - Scanning video 'Cardinal - S01E02 - Delorme WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-22 12:17:22,970 - 16872 - INFO - Scanning video 'Cardinal - S01E05 - Keith WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-22 12:17:23,020 - 16872 - INFO - Scanning video 'Cardinal - S01E04 - Woody WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-22 12:17:23,069 - 16872 - INFO - Scanning video 'Cardinal - S02E02 - Kevin HDTV-720p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-22 12:17:47,015 - 16872 - INFO - Addic7ed using authentication serice.
2018-01-22 12:17:47,789 - 16872 - INFO - Listing subtitles with provider 'opensubtitles' for video <Episode [u'TV Library', 2x2]> with languages set([<Language [en]>])
2018-01-22 12:17:48,194 - 16872 - INFO - Found 1 subtitle(s) on opensubtitles
2018-01-22 12:17:48,194 - 16872 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'TV Library', 2x2]> with languages set([<Language [en]>])
2018-01-22 12:17:48,591 - 16872 - INFO - Found 0 subtitle(s) on addic7ed
2018-01-22 12:17:48,591 - 16872 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'TV Library', 2x2]> with languages set([<Language [en]>])
2018-01-22 12:17:48,592 - 16872 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-22 12:17:48,617 - 16872 - INFO - Downloading subtitle <OpenSubtitlesSubtitle [en]> with score 46 into u'Cardinal - S02E02 - Kevin HDTV-720p.srt'
2018-01-22 12:18:07,936 - 16872 - INFO - Successfully placed Cardinal - S02E02 - Kevin HDTV-720p.srt
2018-01-22 12:18:07,959 - 16872 - INFO - Post processing subtitles Cardinal - S02E02 - Kevin HDTV-720p.srt encoding.
2018-01-22 12:18:07,980 - 16872 - INFO - Scanning video 'Cardinal - S02E03 - Terri HDTV-720p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-22 12:18:20,375 - 16872 - INFO - Addic7ed using authentication serice.
2018-01-22 12:18:21,236 - 16872 - INFO - Listing subtitles with provider 'opensubtitles' for video <Episode [u'TV Library', 2x3]> with languages set([<Language [en]>])
2018-01-22 12:18:22,937 - 16872 - INFO - Found 1 subtitle(s) on opensubtitles
2018-01-22 12:18:22,938 - 16872 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'TV Library', 2x3]> with languages set([<Language [en]>])
2018-01-22 12:18:24,046 - 16872 - INFO - Found 0 subtitle(s) on addic7ed
2018-01-22 12:18:24,046 - 16872 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'TV Library', 2x3]> with languages set([<Language [en]>])
2018-01-22 12:18:24,046 - 16872 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-22 12:18:24,059 - 16872 - INFO - Downloading subtitle <OpenSubtitlesSubtitle [en]> with score 46 into u'Cardinal - S02E03 - Terri HDTV-720p.srt'
2018-01-22 12:18:34,306 - 16872 - INFO - Successfully placed Cardinal - S02E03 - Terri HDTV-720p.srt
2018-01-22 12:18:34,309 - 16872 - INFO - Post processing subtitles Cardinal - S02E03 - Terri HDTV-720p.srt encoding.
2018-01-22 12:18:34,332 - 16872 - INFO - Scanning video 'Cardinal - S02E01 - Red HDTV-720p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-22 12:18:48,717 - 16872 - INFO - Addic7ed using authentication serice.
2018-01-22 12:18:50,065 - 16872 - INFO - Listing subtitles with provider 'opensubtitles' for video <Episode [u'TV Library', 2x1]> with languages set([<Language [en]>])
2018-01-22 12:18:54,832 - 16872 - INFO - Found 1 subtitle(s) on opensubtitles
2018-01-22 12:18:54,832 - 16872 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'TV Library', 2x1]> with languages set([<Language [en]>])
2018-01-22 12:18:55,713 - 16872 - INFO - Found 0 subtitle(s) on addic7ed
2018-01-22 12:18:55,714 - 16872 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'TV Library', 2x1]> with languages set([<Language [en]>])
2018-01-22 12:18:55,716 - 16872 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-22 12:18:55,729 - 16872 - INFO - Downloading subtitle <OpenSubtitlesSubtitle [en]> with score 46 into u'Cardinal - S02E01 - Red HDTV-720p.srt'
2018-01-22 12:19:12,190 - 16872 - INFO - Successfully placed Cardinal - S02E01 - Red HDTV-720p.srt
2018-01-22 12:19:12,207 - 16872 - INFO - Post processing subtitles Cardinal - S02E01 - Red HDTV-720p.srt encoding.
2018-01-22 12:19:12,232 - 16872 - INFO - Scanning video 'Cardinal - S01E06 - Catherine WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'

```

**Comment by bossanova808** [comment]
ok the mangled filename is a utf-8 vs 16 thing - I am using windows/NTFS, but apparently that should be set to utf-8 not utf-16 despite the advice in the .ini :)

**Comment by caronc** [comment]
> ....this issue is that is seems to be looking for TV Library as the series name, rather than the series Cardinal - or so the log seems to imply. But I've checked the subs downloaded, and they are indeed for Cardinal. So think it's more of a log output issue than a real issue maybe...

I think what is happening is that script is trying to to follow the standard directory structure most use for TV Shows (syntax is usually _TVShow/S01/EpisodeS01E01.mkv_). So this is why your _TV Library_ directory is getting picked up as the _TVShow_. Let me see if there is a way to build in some clever logic for detecting when the Season folder (in the example: S01) is missing. Alternatively, if you fix this directory structure and try again it should work for you.

As per that funky filename your seeing too in the logs; it's definitely there! :wink:.  Perhaps it's marked as hidden to your filesystem which is why you can't see it?  Either way, the script is properly moving on as it should since it isn't parseable.

**Comment by bossanova808** [comment]
Thanks for the response

But the season folder does exist, e.g. in this case the full path for the videos is, e.g.:
`I:\TV Library 04\Cardinal\Season 02\Cardinal - S02E01 - Red HDTV-720p.mkv`

(I'm just calling it from the parent folder so it does all seasons)

..that naming structure is absolutely following convention and I have been using that structure with a whole bunch of media players and library builders for a solid 15 years now without issue...so yeah if Sulbiminal is parsing that path and not working out the series name correctly from it... that's odd and indicates perhaps an issue with it's RegEx.  And I suppose that must be what it is doing and yet it does actually find the subs ok in this case, which is odd.

Re: the funny file name - initially I set:
`SystemEncoding: UTF-16`

...per the notes above it in your example ini, as my drives are all NTFS, but as soon as I go back to:
`SystemEncoding: UTF-8`

...those 'files' disappear and there's no further issue.  Python and unicode eh?  Always fun.

**Comment by caronc** [comment]
> But the season folder does exist, 
Doh, yes you're right; i got cocky and overlooked that.  There is still something definitely going wrong with the way the directories are being parsed. So i'll still focus on the same area; but thanks for clarifying that miss on my my part! :smile: 

> Python and unicode eh? Always fun.
lol; sarcasm reapplied... yep! Always fun!

I promise to have a look at this over the weekend.  It's tough to do while at work; but i'll keep you posted on anything i find.

**Comment by bossanova808** [comment]
No hurry at all - it's working fine when called by sab itself, it seems (it's called on the temp download folder in that case) - so this was just mucking about with calling it directly.  I've installed the dev branch of subliminal itself as well, will give that a try directly too....not sure if you're still syncing with uptream.

**Comment by caronc** [comment]
So it turns out the guessing module i'm using (guessit) is using the directory path names to help in guessing the name of the video.  To be safe, i'm only keeping the last 2 directories for detected TV Shows and the current directory for Movies). .. soo:

- ```I:\TV Library 04\Cardinal\Season 02\Cardinal - S02E01 - Red HDTV-720p.mkv``` would actually just search ```Cardinal\Season 02\Cardinal - S02E01 - Red HDTV-720p.mkv```
- For a movie (just as an example: ```I:\Movie Library 01\Movies\Great Movie\Great Movie HDTV-720p.mkv```) would just search/guess with: ```Great Movie\Great Movie HDTV-720p.mkv```

Hopefully that makes sense.  I did a test using your naming convention with much success! So check out the master branch and have another go at it! Keep me posted!

**Comment by bossanova808** [comment]
Hey! Thanks!

So - progress on the matching, but have hit an issue with writing out the found subs:

```
C:\Utilities\nzb-subliminal>python Subliminal.py -f "I:\TV Library 04\Cardinal"
2018-01-29 11:47:48,243 - 11776 - INFO - Found 10 matched file(s).
2018-01-29 11:47:48,244 - 11776 - INFO - Using advanced search mode
2018-01-29 11:47:48,641 - 11776 - INFO - Scanning video 'Cardinal - S01E01 - Cardinal WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:47:48,801 - 11776 - INFO - Scanning video 'Cardinal - S01E03 - Edie and Eric WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:47:48,954 - 11776 - INFO - Scanning video 'Cardinal - S01E02 - Delorme WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:47:49,099 - 11776 - INFO - Scanning video 'Cardinal - S01E05 - Keith WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:47:49,239 - 11776 - INFO - Scanning video 'Cardinal - S01E04 - Woody WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:47:49,384 - 11776 - INFO - Scanning video 'Cardinal - S01E06 - Catherine WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'

C:\Utilities\nzb-subliminal>python Subliminal.py -f "I:\TV Library 04\Cardinal"
2018-01-29 11:48:47,756 - 10232 - INFO - Found 10 matched file(s).
2018-01-29 11:48:47,756 - 10232 - INFO - Using advanced search mode
2018-01-29 11:48:48,075 - 10232 - INFO - Scanning video 'Cardinal - S01E01 - Cardinal WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:48:48,134 - 10232 - INFO - Scanning video 'Cardinal - S01E03 - Edie and Eric WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-29 11:48:48,197 - 10232 - INFO - Scanning video 'Cardinal - S02E03 - Terri HDTV-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-29 11:49:00,858 - 10232 - INFO - Addic7ed using non-authenticated service.
2018-01-29 11:49:00,861 - 10232 - INFO - Listing subtitles with provider 'opensubtitles' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-29 11:49:01,663 - 10232 - INFO - Found 1 subtitle(s) on opensubtitles
2018-01-29 11:49:01,663 - 10232 - INFO - Listing subtitles with provider 'thesubdb' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-29 11:49:02,367 - 10232 - INFO - Found 0 subtitle(s) on thesubdb
2018-01-29 11:49:02,367 - 10232 - INFO - Listing subtitles with provider 'podnapisi' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-29 11:49:07,806 - 10232 - INFO - Found 4 subtitle(s) on podnapisi
2018-01-29 11:49:07,808 - 10232 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-29 11:49:20,311 - 10232 - INFO - Found 2 subtitle(s) on addic7ed
2018-01-29 11:49:20,311 - 10232 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-29 11:49:22,150 - 10232 - INFO - Found 1 subtitle(s) on tvsubtitles
2018-01-29 11:49:22,223 - 10232 - INFO - Downloading subtitle <OpenSubtitlesSubtitle [en]> with score 46 into u'Cardinal - S02E03 - Terri HDTV-1080p.en.srt'
2018-01-29 11:49:25,821 - 10232 - ERROR - Fatal Exception:
  Traceback (most recent call last):
    File "C:\Utilities\nzb-subliminal\Subliminal\nzbget\ScriptBase.py", line 3038, in run
    exit_code = main_function(*args, **kwargs)
    File "Subliminal.py", line 1999, in main
    use_nzbheaders=False,
    File "Subliminal.py", line 1675, in subliminal_fetch
    move(move_from, expected_file)
    File "C:\Python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
    File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
    File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
  IOError: [Errno 2] No such file or directory: u'c:\\users\\jamy\\appdata\\local\\temp\\nzbget-Jamy\\Cardinal\\Season 02\\Cardinal - S02E03 - Terri HDTV-1080p.en.srt'
```
....looks like it's trying to write to a temp path, not the actual show path.

But definitely looking for the right thing, now, which is a big step forward :) (and again it's working very well with sab itself)

**Comment by caronc** [comment]
Wow, that is really weird! I've never seen that error in with this tool before. It's like it successfully downloaded the subtitles but then can't find them when it goes to move them into their final resting place. Subs download into a temporary directory (so they can be unzipped and what-have-you) and just get moved afterwards.

What OS are you using? Windows 10?  I'll try to reproduce this; hopefully my last commit didn't break everything :fearful:

**Comment by bossanova808** [comment]
Yep, Windows 10.  I rolled back to prior to those two commits and it was ok again (apart from the paths issue)...so I am guessing the issue is in there although it wasn't obvious to me what it was from a quick look at the commits...

**Comment by caronc** [comment]
The problem was the variable names i chose; i over-rode some important already in-use ones (whoops 😊). Giver another go.  I'm very confident in this last push.

**Comment by bossanova808** [comment]
Yep that is all good it seems - thanks!

Not sure why it is saying opensubtitles is not available...but other than that oddness, all seems fine!

```
C:\Utilities\SAB Post Processing Scripts>python Subliminal.py -f "I:\TV Library 04\Cardinal"
2018-01-31 12:20:24,914 - 11656 - INFO - Found 10 matched file(s).
2018-01-31 12:20:24,914 - 11656 - INFO - Using advanced search mode
2018-01-31 12:20:25,233 - 11656 - INFO - Scanning video 'Cardinal - S01E01 - Cardinal WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:20:25,371 - 11656 - INFO - Scanning video 'Cardinal - S01E03 - Edie and Eric WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:20:25,538 - 11656 - INFO - Scanning video 'Cardinal - S02E03 - Terri HDTV-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-31 12:20:38,795 - 11656 - WARNING - Provider 'opensubtitles' is not available, discarding it
2018-01-31 12:20:38,828 - 11656 - INFO - Addic7ed using authentication serice.
2018-01-31 12:20:40,033 - 11656 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-31 12:20:46,924 - 11656 - INFO - Found 1 subtitle(s) on tvsubtitles
2018-01-31 12:20:46,924 - 11656 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'Cardinal', 2x3]> with languages set([<Language [en]>])
2018-01-31 12:20:59,451 - 11656 - INFO - Found 2 subtitle(s) on addic7ed
2018-01-31 12:20:59,451 - 11656 - INFO - Downloading subtitle <TVsubtitlesSubtitle [en]> with score 35 into u'Cardinal - S02E03 - Terri HDTV-1080p.srt'
2018-01-31 12:21:03,624 - 11656 - INFO - Successfully placed Cardinal - S02E03 - Terri HDTV-1080p.srt
2018-01-31 12:21:03,625 - 11656 - INFO - Post processing subtitles Cardinal - S02E03 - Terri HDTV-1080p.srt encoding.
2018-01-31 12:21:03,647 - 11656 - INFO - Scanning video 'Cardinal - S01E02 - Delorme WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:21:03,874 - 11656 - INFO - Scanning video 'Cardinal - S01E05 - Keith WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:21:04,016 - 11656 - INFO - Scanning video 'Cardinal - S01E04 - Woody WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:21:04,158 - 11656 - INFO - Scanning video 'Cardinal - S02E02 - Kevin HDTV-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-31 12:21:06,068 - 11656 - WARNING - Provider 'opensubtitles' is not available, discarding it
2018-01-31 12:21:06,069 - 11656 - INFO - Addic7ed using authentication serice.
2018-01-31 12:21:06,823 - 11656 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Cardinal', 2x2]> with languages set([<Language [en]>])
2018-01-31 12:21:08,322 - 11656 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-31 12:21:08,322 - 11656 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'Cardinal', 2x2]> with languages set([<Language [en]>])
2018-01-31 12:21:09,332 - 11656 - INFO - Found 2 subtitle(s) on addic7ed
2018-01-31 12:21:09,334 - 11656 - INFO - Downloading subtitle <Addic7edSubtitle [en]> with score 35 into u'Cardinal - S02E02 - Kevin HDTV-1080p.srt'
2018-01-31 12:21:13,338 - 11656 - INFO - Successfully placed Cardinal - S02E02 - Kevin HDTV-1080p.srt
2018-01-31 12:21:13,339 - 11656 - INFO - Post processing subtitles Cardinal - S02E02 - Kevin HDTV-1080p.srt encoding.
2018-01-31 12:21:13,361 - 11656 - INFO - Scanning video 'Cardinal - S02E01 - Red HDTV-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-31 12:21:16,052 - 11656 - WARNING - Provider 'opensubtitles' is not available, discarding it
2018-01-31 12:21:16,052 - 11656 - INFO - Addic7ed using authentication serice.
2018-01-31 12:21:16,852 - 11656 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Cardinal', 2x1]> with languages set([<Language [en]>])
2018-01-31 12:21:18,450 - 11656 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-31 12:21:18,450 - 11656 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'Cardinal', 2x1]> with languages set([<Language [en]>])
2018-01-31 12:21:19,375 - 11656 - INFO - Found 2 subtitle(s) on addic7ed
2018-01-31 12:21:19,375 - 11656 - INFO - Downloading subtitle <Addic7edSubtitle [en]> with score 35 into u'Cardinal - S02E01 - Red HDTV-1080p.srt'
2018-01-31 12:21:24,140 - 11656 - INFO - Successfully placed Cardinal - S02E01 - Red HDTV-1080p.srt
2018-01-31 12:21:24,141 - 11656 - INFO - Post processing subtitles Cardinal - S02E01 - Red HDTV-1080p.srt encoding.
2018-01-31 12:21:24,163 - 11656 - INFO - Scanning video 'Cardinal - S01E06 - Catherine WEBDL-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 01'
2018-01-31 12:21:24,345 - 11656 - INFO - Scanning video 'Cardinal - S02E04 - Toof HDTV-1080p.mkv' in 'I:\\TV Library 04\\Cardinal\\Season 02'
2018-01-31 12:21:26,318 - 11656 - WARNING - Provider 'opensubtitles' is not available, discarding it
2018-01-31 12:21:26,319 - 11656 - INFO - Addic7ed using authentication serice.
2018-01-31 12:21:27,188 - 11656 - INFO - Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Cardinal', 2x4]> with languages set([<Language [en]>])
2018-01-31 12:21:28,515 - 11656 - INFO - Found 0 subtitle(s) on tvsubtitles
2018-01-31 12:21:28,515 - 11656 - INFO - Listing subtitles with provider 'addic7ed' for video <Episode [u'Cardinal', 2x4]> with languages set([<Language [en]>])
2018-01-31 12:21:30,016 - 11656 - INFO - Found 2 subtitle(s) on addic7ed
2018-01-31 12:21:30,017 - 11656 - INFO - Downloading subtitle <Addic7edSubtitle [en]> with score 35 into u'Cardinal - S02E04 - Toof HDTV-1080p.srt'
2018-01-31 12:21:34,986 - 11656 - INFO - Successfully placed Cardinal - S02E04 - Toof HDTV-1080p.srt
2018-01-31 12:21:35,012 - 11656 - INFO - Post processing subtitles Cardinal - S02E04 - Toof HDTV-1080p.srt encoding.
```

**Comment by caronc** [comment]
I don't think that's a bug; it looks like opensubtitles is actually down right now (here is what i get when i visit the site):
![opensubtitles](https://user-images.githubusercontent.com/850374/35600754-94fb7814-05fd-11e8-95af-6443c7872844.png)

**Comment by bossanova808** [comment]
Ah indeed, seems obvious now.  Coolio - I'll close thus off and thanks again!
