### ISSUE TITLE
subliminal is failing on all downloads now

### ISSUE THREAD

**Issue by oppsig** [caronc/nzb-subliminal#55]
```
Sat May 12 2018 22:20:02	INFO	Executing post-process-script nzbget-subliminal/Subliminal.py for ************
Sat May 12 2018 22:20:03	INFO	Subliminal: Traceback (most recent call last):
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal.py", line 395, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from apprise import Apprise
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/__init__.py", line 31, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from .plugins.NotifyBase import NotifyBase
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/plugins/__init__.py", line 44, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from .NotifyTwitter.NotifyTwitter import NotifyTwitter
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/plugins/NotifyTwitter/__init__.py", line 17, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from . import NotifyTwitter
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/plugins/NotifyTwitter/NotifyTwitter.py", line 19, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from . import tweepy
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/plugins/NotifyTwitter/tweepy/__init__.py", line 16, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from .auth import OAuthHandler, AppAuthHandler
Sat May 12 2018 22:20:03	INFO	Subliminal:   File "/opt/ppscripts/nzbget-subliminal/Subliminal/apprise/plugins/NotifyTwitter/tweepy/auth.py", line 9, in <module>
Sat May 12 2018 22:20:03	INFO	Subliminal:     from requests_oauthlib import OAuth1Session, OAuth1
Sat May 12 2018 22:20:03	INFO	Subliminal: ImportError: No module named requests_oauthlib
Sat May 12 2018 22:20:03	ERROR	Post-process-script nzbget-subliminal/Subliminal.py for ************ failed (terminated with unknown status)
```

**Comment by caronc** [comment]
Good find and thank you for bringing this up! Try checking out the master branch and giving it another go

**Comment by oppsig** [comment]
Will do not able to test before end of month, but will update when I do!

**Comment by oppsig** [comment]
Yes, everything is fine now :)
