### ISSUE TITLE
Markdown Failure

### ISSUE THREAD

**Issue by dmacdonald82** [caronc/nzb-subliminal#56]
Running the script via CMD or integrated with SABNZB, I get the following error

`C:\nzb2media>python Subliminal.py -s -f -S "DIRECTORY_OBFUSCATED_BY_USER"
Traceback (most recent call last):
  File "Subliminal.py", line 395, in <module>
    from apprise import Apprise
  File "C:\nzb2media\Subliminal\apprise\__init__.py", line 33, in <module>
    from .Apprise import Apprise
  File "C:\nzb2media\Subliminal\apprise\Apprise.py", line 24, in <module>
    from markdown import markdown
ImportError: No module named markdown`

Any ideas? I grabbed the ZIP file directly from the master branch, created an INI file from your sample, and tried to run with this result. Running on Server 2008R2

**Comment by caronc** [comment]
:flushed: thank you for creating this ticket.  This package was probably missing for some time now and I never noticed since it was always globally available to me. 

Try checking out the master and giving it another go.

**Comment by dmacdonald82** [comment]
Thanks! Good now, works as expected.. Thanks
