### ISSUE TITLE
Subliminal: TypeError: unsupported operand type(s) for -=: 'str' and 'int'

### ISSUE THREAD

**Issue by sguillope** [caronc/nzb-subliminal#57]
Using `master` at 6946b29, I get the following error every time the post-processing is run:
```
ERROR	Subliminal: Traceback (most recent call last):
ERROR	Subliminal:   File "/opt/nzbget/scripts/Subliminal/nzbget/ScriptBase.py", line 3057, in run
INFO	Subliminal:     exit_code = main_function(*args, **kwargs)
ERROR	Subliminal:   File "/opt/nzbget/scripts/Subliminal.py", line 1990, in postprocess_main
INFO	Subliminal:     overwrite=overwrite,
ERROR	Subliminal:   File "/opt/nzbget/scripts/Subliminal.py", line 1616, in subliminal_fetch
INFO	Subliminal:     throttle_threshold -= 1
ERROR	Subliminal: TypeError: unsupported operand type(s) for -=: 'str' and 'int'
INFO	Subliminal: [DEBUG] Exiting with return code: 94
```

And unfortunately it makes NZBGet cancel and delete the download :(

**Comment by caronc** [comment]
great job @sguillope! Thank you for the pull request.
