### ISSUE TITLE
Error in tvsubtitles.net

### ISSUE THREAD

**Issue by roobandev** [caronc/nzb-subliminal#68]
Below is the error when it searches for subtitle in tvsubtitles.net

```
2018-12-26 08:09:31,006 - 17647 - ERROR - Unexpected error in provider 'tvsubtitles'
Traceback (most recent call last):
  File "/home/nzb-subliminal/Subliminal/subliminal/api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/home/nzb-subliminal/Subliminal/subliminal/providers/tvsubtitles.py", line 177, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.episode) if s.language in languages]
  File "/home/nzb-subliminal/Subliminal/subliminal/providers/tvsubtitles.py", line 161, in query
    show_id = self.find_show_id(series)
  File "/home/nzb-subliminal/Subliminal/dogpile/cache/region.py", line 1013, in decorate
    should_cache_fn)
  File "/home/nzb-subliminal/Subliminal/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/home/nzb-subliminal/Subliminal/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/home/nzb-subliminal/Subliminal/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/home/nzb-subliminal/Subliminal/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/home/nzb-subliminal/Subliminal/dogpile/cache/region.py", line 612, in gen_value
    created_value = creator()
  File "/home/nzb-subliminal/Subliminal/dogpile/cache/region.py", line 1009, in creator
    return fn(*arg, **kw)
  File "/home/nzb-subliminal/Subliminal/subliminal/providers/tvsubtitles.py", line 106, in find_show_id
    soup = self.request('/search.php', data=data, method='POST')
  File "/home/nzb-subliminal/Subliminal/subliminal/providers/tvsubtitles.py", line 88, in request
    r = self.session.request(method, self.server + url, params=params, data=data, timeout=10)
  File "/home/nzb-subliminal/Subliminal/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nzb-subliminal/Subliminal/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/nzb-subliminal/Subliminal/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.tvsubtitles.net', port=80): Max retries exceeded with url: /search.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f94fea90350>, 'Connection to www.tvsubtitles.net timed out. (connect timeout=10)'))
```

**Comment by caronc** [comment]
Hi,

Thanks for reporting this;  is it happening every time, or just now and then?  Sometimes these sites go down for a bit (for maintenance).  So if you're checking around that time it may fail.
