### ISSUE TITLE
im trying to setup this with sabnzbd {No module named extern}

### ISSUE THREAD

**Issue by ecto1a2003** [caronc/nzb-subliminal#75]
:beetle: **Describe the bug**
im trying to setup this with sabnzbd, keep getting error about the extern as listed above.

:bulb: **Screenshots and Logs**

C:\Python27\lib\site-packages\apprise\plugins\NotifySimplePush.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography.hazmat.primitives import padding
Traceback (most recent call last):
File "C:\Program Files\SABnzbd\scripts\Subliminal.py", line 416, in <module>
from apprise import Apprise
File "C:\Python27\lib\site-packages\apprise\__init__.py", line 55, in <module>
from .Apprise import Apprise
File "C:\Python27\lib\site-packages\apprise\Apprise.py", line 29, in <module>
from markdown import markdown
File "C:\Python27\lib\site-packages\markdown\__init__.py", line 28, in <module>
from .__meta__ import __version__, __version_info__
File "C:\Python27\lib\site-packages\markdown\__meta__.py", line 26, in <module>
from pkg_resources.extern import packaging
ImportError: No module named extern

:computer: **Your System Details:**
 - OS: [e.g. RedHat v8.0]
 - Python Version: [e.g. Python v2.7]

:crystal_ball: **Additional context**

**Comment by caronc** [comment]
What version of SABnzbd are you using? v3.x is not compatible with Python v2.7. If you upgrade your version of SABnzbd and Python, you shouldn't have a problem.

**Comment by caronc** [comment]
This project is somewhat abandoned.; it needs a lot of work to get working properly with Python v3.x (as Python v2.x is definitely not something you want to be using these days).  I think there are better alternatives out there right now though.  Have you had a look at [Bazarr](https://github.com/morpheus65535/bazarr)?

**Comment by ecto1a2003** [comment]
i counldnt even get bazarr to start, plus i dont use radarr or sonarr. im on 3.1.1 of sabnzbd

**Comment by caronc** [comment]
I'm really sorry, :slightly_frowning_face: 

I'd love to find time and reboot this project, but I just haven't found the time.  I'm glad you're using SABnzbd v3.1.1 though, that's good.  I'm surprised it's working for you on Python v2.7 though (based on your error messages); I was under the understanding that it only worked using Python v3.x.

Either way_, At this time_ I'm afraid I can't give you any good answer to your dilemma ... :slightly_frowning_face:

**Comment by ecto1a2003** [comment]
bummer, oh well. any advice for bazarr i installed it but nada

**Comment by caronc** [comment]
You should ask in their Discord channel; they're pretty active there and they're all great people! :+1: 
[Here is a link to their Discord Community](https://discord.gg/MH2e2eb)
